# Generated by Django 4.0 on 2021-12-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='aprove',
            new_name='approve',
        ),
    ]
